name: Delete JFrog artifacts on branches deletion with JFrog token in GitHub Secrets

on:
  delete:
    branches:
      # Run when any short-lived branch is deleted, so we do not delete potentially
      # important artifacts generated on main branches
      - '!dev'
      - '!master'
      - '!main'

env:
  ARTIFACTORY_ADDR: "https://xxxx.jfrog.io/artifactory"
  ARTIFACTORY_REPOSITORY: "your-docker-repository"
  ARTIFACTORY_PATH: "path/to/your/artifact"
  ARTIFACTORY_FILENAME_PATTERN: "tag-pattern-*"

jobs:
  artifactory_cleanup:
    runs-on: ubuntu-latest
    name: Clean with GitHub Secrets
    steps:
      - name: "Cleanup JFrog artifacts"
        uses: adeo/cleanup-artifactory-action@v1
        with:
          artifactoryUrl: "${{ env.ARTIFACTORY_ADDR }}"
          # Update this with the name of your GitHub Secret
          token: "${{ secrets.JFROG_API_KEY }}"
          repository: "${{env.ARTIFACTORY_REPOSITORY }}"
          path: "${{ env.ARTIFACTORY_PATH }}"
          pattern: "${{ env.ARTIFACTORY_PATTERN_FILENAME }}-*"
          # By default dryRun is set to "true", you need to uncomment the following
          # line and set it to "false" for the action to actually delete artifacts,
          # otherwise it will just list any matching artifact (useful to check your
          # pattern)
          # dryRun: "true"
