name: Delete JFrog artifacts on branches deletion with JFrog token in Hashicorp Vault

on:
  delete:
    branches:
      # Run when any short-lived branch is deleted, so we do not delete potentially
      # important artifacts generated on main branches
      - '!dev'
      - '!master'
      - '!main'

env:
  # See the Vault action documentation for more information
  # https://github.com/hashicorp/vault-action
  VAULT_ADDR: "https://your.vault.url"
   # If you use Vault Enterprise and its namespaces feature
  VAULT_NAMESPACE: "xxxx/app-namespace"
  # If you store the API key in a KV v2 secrets engine, the path is
  # <mount point, usually 'secret'>/data/<path/to/secret>
  VAULT_JFROG_SECRET_PATH: "secret/data/path/to/jfrog"
  VAULT_JFROG_SECRET_KEY: "api-key"

  ARTIFACTORY_ADDR: "https://xxxx.jfrog.io/artifactory"
  ARTIFACTORY_REPOSITORY: "your-docker-repository"
  ARTIFACTORY_PATH: "path/to/your/artifact"
  ARTIFACTORY_FILENAME_PATTERN: "tag-pattern"

jobs:
  artifactory_cleanup:
    runs-on: ubuntu-latest
    name: Clean with Vault secrets
    steps:
      - name: Get Vault secrets
        uses: hashicorp/vault-action@v2.1.2
        id: vault
        with:
          url: "${{ env.VAULT_ADDR }}"
          namespace: "${{ env.VAULT_NAMESPACE }}"
          method: approle
          roleId: "${{ secrets.VAULT_ROLE_ID }}"
          secretId: "${{ secrets.VAULT_SECRET_ID }}"
          secrets: |
            ${{ env.VAULT_JFROG_SECRET_PATH }} ${{ env.VAULT_JFROG_SECRET_KEY }} | JFROG_API_KEY ;


      - name: "Cleanup JFrog artifacts"
        uses: adeo/cleanup-artifactory-action@v1
        with:
          artifactoryUrl: "${{ env.ARTIFACTORY_ADDR }}"
          token: "${{ steps.vault.outputs.JFROG_API_KEY }}"
          repository: "${{env.ARTIFACTORY_REPOSITORY }}"
          path: "${{ env.ARTIFACTORY_PATH }}"
          pattern: "${{ env.ARTIFACTORY_FILENAME_PATTERN }}*"
          # By default dryRun is set to "true", you need to uncomment the following
          # line and set it to "false" for the action to actually delete artifacts,
          # otherwise it will just list any matching artifact (useful to check your
          # pattern)
          # dryRun: "true"
